version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - API_KEY=${API_KEY}  # Will use value from .env file
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

# For local development, you can run:
# docker-compose up --build